// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDiWYXmGXtmgEXzRsf3b3bnO_1HA5dqq8',
    appId: '1:390174751424:web:1d690d9c3eafe1ba1acb25',
    messagingSenderId: '390174751424',
    projectId: 'acne-000',
    authDomain: 'acne-000.firebaseapp.com',
    storageBucket: 'acne-000.firebasestorage.app',
    measurementId: 'G-93CJKPR47W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1DboEY5iKiLEqlQ42uNAqMK5-bC0P-RY',
    appId: '1:390174751424:android:50c695027677f71d1acb25',
    messagingSenderId: '390174751424',
    projectId: 'acne-000',
    storageBucket: 'acne-000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8FbjzCkIN39GHjkY2AYW_SLVGP7eVti4',
    appId: '1:390174751424:ios:91da9b5509c3c4821acb25',
    messagingSenderId: '390174751424',
    projectId: 'acne-000',
    storageBucket: 'acne-000.firebasestorage.app',
    iosBundleId: 'com.example.acne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8FbjzCkIN39GHjkY2AYW_SLVGP7eVti4',
    appId: '1:390174751424:ios:91da9b5509c3c4821acb25',
    messagingSenderId: '390174751424',
    projectId: 'acne-000',
    storageBucket: 'acne-000.firebasestorage.app',
    iosBundleId: 'com.example.acne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDiWYXmGXtmgEXzRsf3b3bnO_1HA5dqq8',
    appId: '1:390174751424:web:1cf0ede7c348ae421acb25',
    messagingSenderId: '390174751424',
    projectId: 'acne-000',
    authDomain: 'acne-000.firebaseapp.com',
    storageBucket: 'acne-000.firebasestorage.app',
    measurementId: 'G-W8353BGW0R',
  );
}
